name: Deploy

on:
    push:
        branches: ['master']

jobs:

    deploy:
        runs-on: ubuntu-latest
        concurrency: deploy # Avoid deploying concurrently
        timeout-minutes: 15
        environment:
            name: prod
            url: https://mnapoli.fr
        steps:

            -   uses: actions/checkout@v4

            -   uses: actions/setup-node@v4
                with:
                    node-version: '16'

            -   name: Cache npm dependencies
                uses: actions/cache@v4
                with:
                    path: ~/.npm # npm cache files are stored in `~/.npm`
                    key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
                    restore-keys: |
                        ${{ runner.OS }}-node-

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.2'
                    coverage: none
                    tools: bref/cli:^1

            -   uses: ramsey/composer-install@v1
                with:
                    composer-options: '--optimize-autoloader --no-dev'

            -   run: npm ci

            -   name: Compile the assets
                run: npm run production

            -   run: bref deploy --env=prod
                env:
                    BREF_TOKEN: ${{ secrets.BREF_TOKEN }}
